# lightweight Node image
FROM node:20-alpine

# app directory inside container
WORKDIR /app

# copy package files first (cache go brrr)
COPY package*.json ./

# install deps
RUN npm ci

# copy the rest of the app
COPY . .

# Vite dev server port
EXPOSE 3000

# run dev server
CMD ["npm", "run", "dev"]
