"use client"

import {
  BookOpen,
  ChevronRight,
  Flag,
  GraduationCap,
  Home,
  Layers,
  LogOut,
  Menu,
  Moon,
  Settings,
  Sun,
  Target,
  User,
  X,
  Check,
  AlertCircle,
  Flame,
  Trophy,
  Clock,
  TrendingUp,
  FileText,
  Play,
  Bookmark,
  Search,
  Bell,
  ChevronDown,
  MoreHorizontal,
  Eye,
  EyeOff,
  Mail,
  Lock,
  ArrowRight,
  Sparkles,
  Zap,
  BarChart3,
  Calendar,
  Star,
  Heart,
  Share2,
  Download,
  Filter,
  Grid3X3,
  List,
  RefreshCw,
  CheckCircle2,
  XCircle,
  Info,
  HelpCircle,
  Camera,
  Edit3,
  Save,
  Trash2,
  Plus,
  Minus,
  ChevronLeft,
  ChevronsLeft,
  ChevronsRight,
  ExternalLink,
  Copy,
  RotateCcw,
  FolderOpen,
  MessageSquare,
  Send,
  Bot,
  Lightbulb,
  ArrowLeft,
  ChevronUp,
  Gamepad2,
  Timer,
  Award,
  type LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  // Navigation
  home: Home,
  dashboard: Layers,
  materials: BookOpen,
  practice: Target,
  profile: User,
  settings: Settings,
  menu: Menu,
  close: X,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  externalLink: ExternalLink,
  arrowLeft: ArrowLeft,
  
  // Actions
  logout: LogOut,
  search: Search,
  bell: Bell,
  filter: Filter,
  grid: Grid3X3,
  list: List,
  refresh: RefreshCw,
  copy: Copy,
  edit: Edit3,
  save: Save,
  delete: Trash2,
  plus: Plus,
  minus: Minus,
  download: Download,
  share: Share2,
  reset: RotateCcw,
  folder: FolderOpen,
  send: Send,
  
  // Status
  check: Check,
  checkCircle: CheckCircle2,
  xCircle: XCircle,
  alertCircle: AlertCircle,
  info: Info,
  help: HelpCircle,
  flag: Flag,
  
  // Theme
  sun: Sun,
  moon: Moon,
  
  // Content
  graduationCap: GraduationCap,
  flame: Flame,
  trophy: Trophy,
  clock: Clock,
  trendingUp: TrendingUp,
  fileText: FileText,
  play: Play,
  bookmark: Bookmark,
  star: Star,
  heart: Heart,
  sparkles: Sparkles,
  zap: Zap,
  barChart: BarChart3,
  calendar: Calendar,
  moreHorizontal: MoreHorizontal,
  
  // Auth
  eye: Eye,
  eyeOff: EyeOff,
  mail: Mail,
  lock: Lock,
  arrowRight: ArrowRight,
  camera: Camera,
  
  // Chat/AI
  messageSquare: MessageSquare,
  bot: Bot,
  lightbulb: Lightbulb,
  
  // Games
  gamepad: Gamepad2,
  timer: Timer,
  award: Award,
} as const
